version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /venv
    environment:
      DJANGO_SETTINGS_MODULE: pairupbackend.settings
      POSTGRES_DB: pairup
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pairup
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
